openapi: 3.0.3
info:
  title: STD23104 - TD4
  version: "1.0.6"
servers:
  - url: https://localhost.std23104.com
paths:
  /meals:
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
      responses:
        200:
          description: List of meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Meal"
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/CreateMeal"
        required: true
      responses:
        200:
          description: List of created meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Meal"
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Meal"
        required: true
      responses:
        200:
          description: List of updated meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Meal"
    delete:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/MealIdentifier"
        required: true
      responses:
        200:
          description: List of deleted meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Meal"
  /customers/{customerId}/orders:
    get:
      parameters:
        - in: path
          name: customerId
          schema:
            type: string
          required: true
      responses:
        200:
          description: List of orders for the specified customer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
    post:
      parameters:
        - in: path
          name: customerId
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
        required: true
      responses:
        200:
          description: Order created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
    put:
      parameters:
        - in: path
          name: customerId
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
        required: true
      responses:
        200:
          description: Order updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
components:
  schemas:
    Meal:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
          format: float
    MealIdentifier:
      type: object
      properties:
        id:
          type: string
    CreateMeal:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          format: float
    Order:
      type: object
      properties:
        reference:
          type: string
        meals:
          type: array
          items:
            type: object
            properties:
              meal:
                $ref: "#/components/schemas/Meal"
              quantity:
                type: integer
        orderDatetime:
          type: string
          format: date-time
