openapi: 3.0.3
info:
  title: STD23104 - TD5
  version: "1.0.8"
servers:
  - url: https://localhost.std23104.com
paths:
  /meals:
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
      responses:
        200:
          description: List of meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Meal"
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/CreateMeal"
        required: true
      responses:
        200:
          description: List of created meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Meal"
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Meal"
        required: true
      responses:
        200:
          description: List of updated meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Meal"
    delete:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/MealIdentifier"
        required: true
      responses:
        200:
          description: List of deleted meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Meal"
  /customers/{customerId}:
    get:
      summary: Get customer by ID
      parameters:
        - in: path
          name: customerId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Customer details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
    put:
      summary: Update the entire customer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
        required: true
      responses:
        200:
          description: Updated customer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
    patch:
      summary: Partially update the customer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PartialCustomerUpdate"
        required: true
      responses:
        200:
          description: Partially updated customer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
components:
  schemas:
    Meal:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
          format: float
    CreateMeal:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
          format: float
    MealIdentifier:
      type: object
      properties:
        id:
          type: string
    Order:
      type: object
      properties:
        id:
          type: string
        reference:
          type: string
        meals:
          type: array
          items:
            $ref: "#/components/schemas/OrderMeal"
        orderDatetime:
          type: string
          format: date-time
    CreateOrder:
      type: object
      properties:
        reference:
          type: string
        meals:
          type: array
          items:
            $ref: "#/components/schemas/CreateOrderMeal"
    UpdateOrder:
      type: object
      properties:
        reference:
          type: string
        meals:
          type: array
          items:
            $ref: "#/components/schemas/UpdateOrderMeal"
    OrderMeal:
      type: object
      properties:
        mealId:
          type: string
        quantity:
          type: integer
    CreateOrderMeal:
      type: object
      properties:
        mealId:
          type: string
        quantity:
          type: integer
    UpdateOrderMeal:
      type: object
      properties:
        mealId:
          type: string
        quantity:
          type: integer
    Customer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer
      required:
        - id
        - name
        - age
    PartialCustomerUpdate:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer
      required:
        - id
